server:
    port: 8080
spring:
    application:
        name: '@project.artifactId@'
    jackson:
        serialization:
            WRITE_EMPTY_JSON_ARRAYS: false
            
api:
  name: customerBill
  version: '@project.version@'

#bscs:
#  provider: remote
#remoteBackendFactory:
#  address: http://localhost:9999/services/bscs

