server:
    port: 8582
spring:
    application:
        name: '@project.artifactId@'

    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
            WRITE_EMPTY_JSON_ARRAYS: false
            
api:
  name: productOrdering
  version: '@project.version@'     